In [112]:
import math
import numpy as np

In [113]:
%whos # List all variables of the notebook

No variables match your requested type.


In [114]:
math.pi

3.141592653589793

In [115]:
math.sin(0)

0.0

In [116]:
math.cos(0)

1.0

In [117]:
lista=[1,2,3,4,5]

In [118]:
for num in range(10):
    print(num)

0
1
2
3
4
5
6
7
8
9


In [119]:
a=np.arange(10)

In [120]:
dir(a) # List all methods of the object

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__o

In [121]:
a.shape

(10,)

In [122]:
matrix=np.arange(15,dtype=np.int32).reshape(3,5) # Create a matrix 3x5

In [123]:
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]], dtype=int32)

In [124]:
matrix[1,2] # Access to the element in the row 1 and column 2

7

In [125]:
matrix[:2,1:3] # Access to the elements in the rows 0 and 1 and columns 1 and 2

array([[1, 2],
       [6, 7]], dtype=int32)

In [126]:
matrix[1:,::2]=999 # Access to the elements in the rows 1 and 2 and columns 0 and 2 and assign 999

In [127]:
np.max(matrix)

999

In [128]:
np.min(matrix)

0

In [129]:
np.max(matrix,axis=0) # Max in each column

array([999,  11, 999,  13, 999], dtype=int32)

In [130]:
np.mean(matrix)

402.8